In [203]:
import numpy as np
import pandas as pd 
import queue

In [261]:
number_of_servers = 50
connections = 200

In [262]:
server_matrix = np.zeros((number_of_servers,number_of_servers), dtype=int)

for i in range(connections):
    row = 0
    col = 0 
    while row == col:
        row = np.random.randint(1,number_of_servers-1)
        col = np.random.randint(1,number_of_servers)
    
    server_matrix[row,col] += 1 

server_matrix[0,1] =1 
server_matrix[4,2]=1
print(server_matrix)

[[0 1 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [284]:
max_server_number = np.amax(server_matrix, axis=0)
print(max_server_number)

[0 1 1 2 1 2 1 2 1 1 1 1 1 1 1 1 1 1 1 1 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 2 1 1 1 1 1]


In [285]:
server_names = []
count = 0

for max_number in max_server_number:
    if count == 0:
        server_names.append("null")
    elif max_number == 1:
        server_names.append("S-" + str(count))
    elif max_number > 1:
        tmp = []
        for i in range(1, max_number+1):
            tmp.append("S-" + str(count)+ "." + str(i))
        server_names.append(tmp)
    else:
        continue
    count += 1


In [283]:
print(len(server_names))

50


In [180]:
# number_cases = 5
# req = ["Request", "Response"]
# max_servers = 2

# with open("data.txt", "w") as file:
#     for i in range(number_cases):
#         count_severs = 0 
#         requests = []
#         responses = []
#         server_sequence = []
#         number_sequence = []
#         server_sequence.append("null")
#         number_sequence.append(0)
#         server_number = np.random.choice(np.nonzero(server_matrix[0])[0])
#         number_sequence.append(server_number)
#         if max_server_number[server_number]==1:
#             server = np.random.choice([server_names[server_number]])
#         else:
#             server = np.random.choice(server_names[server_number])
#         server_sequence.append(server)
#         requests.append(["null", str(server)])
#         file.write("<null, "+ server + ", Request," + str(i) +"> \n")
#         count_severs += 1 
#         while len(server_sequence) <= max_servers+1 :
#             if requests == responses:
#                 break
#             r = np.random.choice(req)
#             if r == "Response":
#                 if [server_sequence[-2] , server_sequence[-1]] not in requests:
#                     continue
#                 file.write("<" + server_sequence[-1] + ", " + server_sequence[-2] + ", Response," +str(i)+ "> \n")
#                 responses.append([server_sequence[-2] , server_sequence[-1]])
#                 number_sequence.append(number_sequence[-2])
                
#             else:
#                 server_number = np.random.choice(np.nonzero(server_matrix[number_sequence[-1]])[0])
#                 number_sequence.append(server_number)
#                 if max_server_number[server_number]==1:
#                     server = np.random.choice([server_names[server_number]])
#                 else:
#                     server = np.random.choice(server_names[server_number])
#                 server_sequence.append(server)
#                 print(server_sequence[-2])
#                 requests.append([server_sequence[-2] ,server])
#                 file.write("<" + server_sequence[-2] + ", " + server + ", Request," +str(i)+"> \n")
    
#         if requests != responses:
#             for j in range(1,len(requests)+1):
#                 if requests[-j] in responses:
#                     continue
#                 else:
#                     file.write("<" + requests[-j][1] + ", " + requests[-j][0] + ", Response," +str(i)+ "> \n")
#         print(i)
#         print(server_sequence)
#         print(requests)
#         print(responses)
#         print(number_sequence)

0
['null', 'S-1']
[['null', 'S-1']]
[['null', 'S-1']]
[0, 1, 0]
S-1
S-2.1
1
['null', 'S-1', 'S-2.1', 'S-1']
[['null', 'S-1'], ['S-1', 'S-2.1'], ['S-2.1', 'S-1']]
[]
[0, 1, 2, 1]
S-1
S-2.2
2
['null', 'S-1', 'S-2.2', 'S-2.2']
[['null', 'S-1'], ['S-1', 'S-2.2'], ['S-2.2', 'S-2.2']]
[['S-1', 'S-2.2']]
[0, 1, 2, 1, 2]
3
['null', 'S-1']
[['null', 'S-1']]
[['null', 'S-1']]
[0, 1, 0]
S-1
S-2.3
4
['null', 'S-1', 'S-2.3', 'S-2.1']
[['null', 'S-1'], ['S-1', 'S-2.3'], ['S-2.3', 'S-2.1']]
[['S-1', 'S-2.3']]
[0, 1, 2, 1, 2]


In [292]:
number_cases = 5 
req = ["Request", "Response"]
max_requests = 3

with open("data.txt", "w") as file:
    for i in range(number_cases):
        
        count_requests = 0 
        q_servers = queue.LifoQueue()
        q_server_numbers = queue.LifoQueue()

        q_servers.put("null")
        q_server_numbers.put(0)

        server_number = np.random.choice(np.nonzero(server_matrix[0])[0])
        q_server_numbers.put(server_number)

        if max_server_number[server_number]==1:
            server = np.random.choice([server_names[server_number]])
        else:
            server = np.random.choice(server_names[server_number])
        q_servers.put(server)

        file.write("<null, "+ server + ", Request," + str(i) +"> \n")

        count_requests += 1
        while count_requests <= max_requests+1:
            if q_servers.queue[-1] == 'null' and count_requests>=1:
                break
            r = np.random.choice(req)
            if r == "Response":
                file.write("<"+ q_servers.queue[-1] +", " + q_servers.queue[-2] + ", Response," + str(i) +"> \n")
                q_servers.get()
                q_server_numbers.get()

            else:
                req_server_number =  np.random.choice(np.nonzero(server_matrix[q_server_numbers.queue[-1]])[0])
                count_requests += 1
                if len(np.nonzero(server_matrix[q_server_numbers.queue[-1]])[0])==1 and req_server_number in q_server_numbers.queue:
                    continue
                while req_server_number in q_server_numbers.queue:
                    req_server_number =  np.random.choice(np.nonzero(server_matrix[q_server_numbers.queue[-1]])[0])
                q_server_numbers.put(req_server_number)
                
                if max_server_number[req_server_number]==1:
                    server = np.random.choice([server_names[req_server_number]])
                else:
                    server = np.random.choice(server_names[req_server_number])

                q_servers.put(server)

                file.write("<" + q_servers.queue[-2] + ", " + server + ", Request," +str(i)+"> \n")
        
        while  not q_servers.empty():
            if q_servers.queue[-1] == 'null':
                break
            else:
                file.write("<"+ q_servers.queue[-1] +", " + q_servers.queue[-2] + ", Response," + str(i) +"> \n")
                q_servers.get()
        

        